//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PanelMaker.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PanelMaker.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to pmEYOEwQSpww/eXzNTyNNvvuIri+YhFWg8pZ4UnYCMfAHU5vL6bXfbz7vocXK8vk3j2/pvxb0/bMX3l5v6/lIr4cPsPm7rKSJdFn/3rpsfKh1+xoniGtrGxcLY0EsRDSPRRdYB4bIUDrcD6XoJxuToFHTM8yvVVv/f4LZdX6jKzIG1gCaTzeJwdBDnNsGAhmi8TejLp4sptzQPkSTY/Kl0x6aRQmYnFd9mARwWcPcCkQTCj+7e1GvBelfXS6/O62QjFImz2HL+s8gh1SzpbZXVu17GlJbHE5scaQ5jD1lVY56M9jq6JiWuIVpN3o2ZV1Wja/QXYYHniol7GVmi3N4F4XX8j7ctKsGVTeDt53n1B/I1MplSpLxaJV2Ki0EUmSiN1NUOYmgMvSG4P70Bc5QJ3RMubrFqRKgOXcDEa3VG8zRezRFKOC4KEyB/Z+M9UN3mHCinp78JdQH0fvjUdcOPWj6ehlvAnOUV2CqHD/+RC9vog5+KOpFi4TfUTgJGMX [rest of string was truncated]&quot;;.
        /// </summary>
        public static string enve {
            get {
                return ResourceManager.GetString("enve", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to cyeq4kD/VUxTBe8pI7yg/bi7h5SsTO51jwszi4wb+lIyDOqhVn64CN17g0eE2JXBjbmOH5oPwUWlecVRi7gRlvfPSFh5HZxIyG2ilAmlV5sfAE4ZtOOBG5HXJ1m6G4YkjxkPRaQwaoGfa746VcdjrOJrYa23sJRYlgFxQ+MtbU5m6Wi7H8f0HkikQJxeu9qOK7PWloFEktvF3b3GgB0dBfj5prK2fSvIY2ZRNnuuWV3vViR1D/ADEUmWPDWIPaJ3ShNx2k0nYbl/4ewuRDq+N0AXpfiR1WMdkEDK/dVcE0kf0MG3hccqKaNLvOESrdQo9Z7zS2lozsOS9yEkUSDTTh5b/kEBtSPJoZqzcsC4ciw1ir2e/KPAATyQe6Na4JXacjl/sf1cVb+783XJcxGqt54qtqqqute5hbSJoWG8HwdOIp4SPXF9LXKPiag8qxNMBwE+95ryOhZiepMcJQdcWCVR1D/VBWTnGjMFnfDlk0Eo9gMreZ6JM4SuM+Z/aIey [rest of string was truncated]&quot;;.
        /// </summary>
        public static string ff {
            get {
                return ResourceManager.GetString("ff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] project {
            get {
                object obj = ResourceManager.GetObject("project", resourceCulture);
                return ((byte[])(obj));
            }
        }
    }
}
